# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBcZKSwBfdbBcjsLyb4VF0NDS7-UnV6-
"""

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom
n = 1000
p = 0.5
x = np.arange(0, n+1)
binomial = binom.pmf(k=x, n=n, p=p)
plt.bar(x, binomial)
plt.xlabel("x" , fontsize=12)
plt.ylabel("probabilidade" , fontsize=12 )
plt.xlim([-1, n+1])
plt.title("Distribuição binominal, n={0}, p={1}" .format(n, p), fontsize=15)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

n = 20
p = 0.5  # Corrigido para ponto decimal
x = np.arange(0, n + 1)
binomial = binom.pmf(k=x, n=n, p=p)  # Corrigido o nome da variável

plt.bar(x, binomial)
plt.xlabel("x", fontsize=12)
plt.ylabel("Probabilidade", fontsize=12)
plt.xlim([-1, n + 1])
plt.title("Distribuição binomial, n={0}, p={1}".format(n, p), fontsize=15)
plt.show()